version: 2
updates:
- package-ecosystem: maven
  directory: "/java"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  assignees:
  - steveclewer
  ignore:
  - dependency-name: com.microsoft.azure:azure-servicebus
    versions:
    - 3.6.0
    - 3.6.1
    - 3.6.2
  - dependency-name: au.com.dius.pact:consumer
    versions:
    - 4.1.15
    - 4.1.16
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: au.com.dius.pact.provider:maven
    versions:
    - 4.1.15
    - 4.1.16
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.39"
    - "8.40"
    - "8.41"
    - 8.41.1
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.0
    - 4.2.2
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.github.spotbugs:spotbugs
    versions:
    - 4.2.0
    - 4.2.1
    - 4.2.2
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/build/azDevops/azure/coverage"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  assignees:
  - ElvenSpellmaker
  rebase-strategy: disabled
- package-ecosystem: maven
  directory: "/api-tests"
  schedule:
    interval: daily
    timezone: Europe/London
  open-pull-requests-limit: 10
  assignees:
  - VitalinaVZdrobau
  ignore:
  - dependency-name: net.serenity-bdd.maven.plugins:serenity-maven-plugin
    versions:
    - 2.3.12
    - 2.3.30
    - 2.3.31
    - 2.4.1
    - 2.4.2
    - 2.4.20
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.owasp:dependency-check-maven
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.39"
    - "8.40"
    - "8.41"
    - 8.41.1
  - dependency-name: au.com.dius.pact.provider:maven
    versions:
    - 4.1.15
    - 4.1.16
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
    versions:
    - 4.2.0
    - 4.2.2
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: net.bytebuddy:byte-buddy
    versions:
    - 1.10.19
    - 1.10.20
    - 1.10.21
    - 1.10.22
  rebase-strategy: disabled
